apiVersion: apps/v1
kind: Deployment
metadata:
  name: guitar-be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guitar-be
  template:
    metadata:
      labels:
        app: guitar-be
    spec:
      containers:
        - name: guitar-be
          image: dpcairns/guitar-be:v9
          env:
          - name: PORT
            value: "3000"
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: DATABASE_URL
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
          

---
apiVersion: v1
kind: Service
metadata:
  name: guitar-be-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: guitar-be
    type: back-end