apiVersion: v1
kind: Pod
metadata:
  name: guitar-be
  labels:
    app: guitar-be
    type: back-end
spec:
  containers:
    - name: guitar-be
      image: dpcairns/guitar-be:latest
      env:
      - name: PORT
        value: "3000"
      - name: DATABASE_URL
        value: "postgres://postgres:guitarpassword@10.108.234.104:5432/guitardb"
      - name: DB_HOST
        value: "private-guitars-db-do-user-1683116-0.a.db.ondigitalocean.com"
      - name: DB_NAME
        value: "defaultdb"
      - name: DB_USER
        value: "doadmin"
      - name: DB_PASSWORD
        value: "dhr94vraj3bovur5"
      - name: DB_PORT 
        value: "25060"
