apiVersion: v1
kind: Pod
metadata:
  name: guitar-be
  labels:
    app: guitar-be
    type: back-end
spec:
  containers:
    - name: guitar-be
      image: dpcairns/guitar-be:latest
      env:
      - name: PORT
        value: "3000"
      - name: DATABASE_URL
        value: "postgres://aimirlbnkltzou:58a3ca982313be68892b0d8e9c84bce27049c60ee2b5adfb1442e2fd649c2ec2@ec2-54-160-120-28.compute-1.amazonaws.com:5432/d2o4terpamskao?sslmode=require"